### ISSUE TITLE
You published your API key

### ISSUE THREAD

**Issue by leviathanch** [iamakashpc/Gemini-Clone#3]
Your API key is in the code there... I'd remove it otherwise folks might run inference with Gemini on your cost

**Comment by iamakashpc** [comment]
Thank you for pointing this out! I’ve removed the API key from the code and will ensure that sensitive information is properly managed going forward. I’m also taking steps to revoke the exposed key and replace it with a secure one.

Thanks again for the heads-up!

**Comment by iamakashpc** [comment]
The API key issue has been addressed. I've updated the code and removed the exposed key. The key has also been revoked and replaced with a secure one. Closing this issue now.
